# =====================================================
# sunat-cpe-api — Perfil CruzCargo
# =====================================================

# --- GRT (REST SEE) ---
# Path base hacia el servicio intermedio GRT para NC.
app.api.grt.path-enviar-betta=http://85.239.233.190:8085/restSEE/api/v2/envio/notacredito
app.api.grt.path-enviar-prd=https://api.example.com/restSEE/api/v2/envio/notacredito

# RUC emisor
app.api.grt.ruc=20559109879

# Credenciales GRT (NO subir a git, idealmente via variable de entorno)
app.api.grt.user=MODDATOS
app.api.grt.pass=MODDATOS

# Timeouts HTTP contra GRT
app.api.grt.connect.timeout.ms=10000
app.api.grt.request.timeout.ms=60000
